### ISSUE TITLE
Removing authentication from an existing cluster doesn't work

### ISSUE THREAD

**Issue by usernkey** [ucloud/redis-cluster-operator#42]
Adding authentication to an existing cluster works and triggers the recycling of the pods as expected.

The other way around (removing the authentication from an existing cluster) seems not working.

It doesn't trigger any recycling of the pods and even if you delete the pods manually they get recreated with the authentication.

Changing the password of an existing cluster doesn't work too

**Comment by polefishu** [comment]
@usernkey 
Please follow the steps below to update your password.

1. Create a new secret to save the password
```
apiVersion: v1
kind: Secret
metadata:
  name: new-password
type: Opaque
data:
  password: MTIzNDU2
```
2. Change the CR's `.spec.passwordSecret.name` field
```
apiVersion: redis.kun/v1alpha1
kind: DistributedRedisCluster
metadata:
  name: example-distributedrediscluster
spec:
  image: redis:5.0.4-alpine
  masterSize: 3
  clusterReplicas: 1
  passwordSecret:
      name: new-password
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 200m
      memory: 100Mi
```
