### ISSUE TITLE
status.nodes is null?

### ISSUE THREAD

**Issue by exherb** [ucloud/redis-cluster-operator#70]
```
status:
  nodes: null
  reason: 'DispatchMasters: missing statefulset drc-back-ad-srv-redis-cluster-0'
  restore:
    backup: null
  status: Failed
```

but the StatefulSet is up and running, and the cluster is remain running

```
kubectl get sts |grep drc-back-ad-srv-redis-cluster-0
drc-back-ad-srv-redis-cluster-0   3/3     141d
```

what cause the issue? and any idea to resolve this?

**Comment by komuw** [comment]
Hi @exherb , how did you solve this?

**Comment by exherb** [comment]
not use this anymore

**Comment by komuw** [comment]
I managed to resolve the issue. Make sure you create 6 PV each with a distinct `path`
```
for i := range 6 {
    ---
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: the-drc-tyk-redis-{{i}}
    spec:
      accessModes:
        - ReadWriteOnce
      capacity:
        storage: 1Gi
      hostPath:
        path: /tmp/{{i}} # This should be distinct
        type: DirectoryOrCreate
      persistentVolumeReclaimPolicy: Retain
      storageClassName: some-storage-class
      volumeMode: Filesystem
}
```
