### ISSUE TITLE
masterSize should be less than or equal to 10

### ISSUE THREAD

**Issue by mattia-badiali** [ucloud/redis-cluster-operator#79]
Hi,

I am testing this operator as a solution for my environment, where I have up to 40 masters, but when I try to apply the following resource:

```
apiVersion: redis.kun/v1alpha1
kind: DistributedRedisCluster
metadata:
  annotations:
    # if your operator run as cluster-scoped, add this annotations
    redis.kun/scope: cluster-scoped
  name: redis-cluster-ucloud
spec:
  # Add fields here
  masterSize: 20
  clusterReplicas: 1
  image: redis:5.0.4-alpine
  config:
    appendonly: "no"
    save: ""
  storage:
    type: persistent-claim
    size: 50Mi
    class: gp2
    deleteClaim: true

```

I get this error:

`The DistributedRedisCluster "redis-cluster-ucloud" is invalid: spec.masterSize: Invalid value: 10: spec.masterSize in body should be less than or equal to 10`

Is it possible to raise this limit by editing the chart values? 

Thanks
