### ISSUE TITLE
how to setting Monitor resources

### ISSUE THREAD

**Issue by jicki** [ucloud/redis-cluster-operator#91]
how to setting Monitor resources ?

```
monitor:
  image: oliver006/redis_exporter:v1.13.1
```

```
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
```
